name: Test that everything works

on:
  workflow_dispatch:
  push:
    branches:
      - lord
    paths:
      - "**.py"
      - "**.yml"
  pull_request:
    paths:
      - "**.py"
      - "**.yml"
jobs:
  check_types:
    runs-on: ubuntu-latest
    name: Check Types
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install everything
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-interaction --no-ansi

      - name: Test
        run: poetry run python -m mypy wtfl/*.py --disallow-any-expr --pretty --show-error-codes
